//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolit
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContextPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContextPage()
        {
            this.MenuSite = new HashSet<MenuSite>();
            this.PriceContentCrosses = new HashSet<PriceContentCross>();
        }
    
        public int Id { get; set; }
        public string Context { get; set; }
        public string Header { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string UrlDescriptImg { get; set; }
        public string SmallDescript { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Descript { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuSite> MenuSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceContentCross> PriceContentCrosses { get; set; }
    }
}
