//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u7716449_monolitEntities : DbContext
    {
        public u7716449_monolitEntities()
            : base("name=u7716449_monolitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MenuSite> MenuSite { get; set; }
        public virtual DbSet<Template> Template { get; set; }
        public virtual DbSet<ContextPage> ContextPage { get; set; }
        public virtual DbSet<CategoryProduct> CategoryProducts { get; set; }
        public virtual DbSet<PriceContentCross> PriceContentCrosses { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
