//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolit
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceContentCross
    {
        public int Id { get; set; }
        public int ContextID { get; set; }
        public int CategoryPriceID { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual ContextPage ContextPage { get; set; }
    }
}
