//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string IE { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currensy { get; set; }
        public string UrlImage { get; set; }
        public int Position { get; set; }
        public bool Visible { get; set; }
        public string Descript { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public string Currency { get; set; }
        public int CategoryId { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
    }
}
